include(ExternalProject)

set(tlRender_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DTLRENDER_TESTS=${TLRENDER_TESTS}
    -DTLRENDER_GCOV=${TLRENDER_GCOV}
    -DTLRENDER_GPROF=${TLRENDER_GPROF}
    -DTLRENDER_PYTHON=${TLRENDER_PYTHON}
    -DTLRENDER_EXR=${TLRENDER_EXR}
    -DTLRENDER_LIBPLACEBO=${TLRENDER_LIBPLACEBO}
    -DTLRENDER_PNG=${TLRENDER_PNG}
    -DTLRENDER_SSL=${TLRENDER_SSL}
    -DTLRENDER_USD=${TLRENDER_USD}
    -DTLRENDER_VK=${TLRENDER_VK})

ExternalProject_Add(
    tlRender
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tlRender
    DEPENDS ${TLRENDER_EXTERNAL_DEPS}
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../..
    LIST_SEPARATOR |
    CMAKE_ARGS ${tlRender_ARGS})
